{% set name = "idiap-devtools" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/idiap-devtools-{{ version }}.tar.gz
  sha256: 97d8b0b1b37ff808d0c24c27069bb64aa16eed2f30e91e2cb18d7d88a2252012

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >=3.9
    - click >=8
    - cookiecutter
    - gitpython
    - packaging
    - python-dateutil
    - python-gitlab
    - pytz
    - pyyaml
    - setuptools
    - tomli
    - tomlkit
    - xdg
    - __unix

test:
  source_files:
    - tests
  imports:
    - idiap_devtools
  commands:
    - pip check
    - pytest -sv tests
  requires:
    - pip
    - pytest
    - git

about:
  home: https://pypi.org/project/idiap-devtools/
  doc_url: https://idiap-devtools.readthedocs.io
  dev_url: https://gitlab.idiap.ch/software/idiap-devtools
  summary: This package contains a *pot-pourri* of various tools required to develop python packages at Idiap's GitLab infrastructure
  license: BSD-3-Clause
  license_file: LICENSES/BSD-3-Clause.txt

extra:
  recipe-maintainers:
    - anjos
