{% set name = "idiap-devtools" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 52fc1f2c5a0f01d48fbe99b8338d7f7b7a842106405feb292ff89f3ae0dfa988

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - conda
    - conda-build
    - mamba
    - boa
    - python >=3.9
    - click >=8
    - cookiecutter
    - gitpython
    - packaging
    - python-dateutil
    - python-gitlab
    - pytz
    - pyyaml
    - setuptools
    - tomli
    - tomlkit
    - xdg
    - __unix

test:
  source_files:
    - tests
  imports:
    - idiap_devtools
  commands:
    - pip check
    - pytest -sv tests
  requires:
    - pip
    - pytest
    - git

about:
  home: https://pypi.org/project/idiap-devtools/
  doc_url: https://idiap-devtools.readthedocs.io
  dev_url: https://gitlab.idiap.ch/software/idiap-devtools
  summary: This package contains a *pot-pourri* of various tools required to develop python packages at Idiap's GitLab infrastructure
  license: BSD-3-Clause
  license_file: LICENSES/BSD-3-Clause.txt

extra:
  recipe-maintainers:
    - anjos
