{% set python_min = "3.11" %}
{% set name = "idiap-devtools" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 292416311ff4afd86bf882a7544e381847fd125934cb04d629d463b639b47813

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - versioningit
    - pip
  run:
    - python >={{ python_min }}
    - click >=8
    - gitpython
    - packaging
    - python-dateutil
    - python-gitlab
    - pytz
    - tomli
    - tomlkit
    - __unix

test:
  source_files:
    - tests
  imports:
    - idiap_devtools
  commands:
    - pip check
    - pytest -sv tests
  requires:
    - pip
    - pytest
    - git
    - python {{ python_min }}

about:
  home: https://pypi.org/project/idiap-devtools/
  doc_url: https://idiap-devtools.readthedocs.io
  dev_url: https://gitlab.idiap.ch/software/idiap-devtools
  summary: This package contains a *pot-pourri* of various tools required to develop python packages at Idiap's GitLab infrastructure
  license: BSD-3-Clause
  license_file: LICENSES/BSD-3-Clause.txt

extra:
  recipe-maintainers:
    - anjos
